config/routes.rb
Rails.application.routes.draw do
  root to: 'fun_facts#index'

  resources :cards, only: :index do
    get :regen, on: :collection
  end

  resources :fun_facts, except: [:show]

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create', as: :oauth_callback
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

end

app/models/card.rb
class Card < ActiveRecord::Base
  CARD_SIZE = 24

  validates :fun_fact_ids, uniqueness: true, length: { is: CARD_SIZE }, card_integrity: true

  def self.generate
    users = User.includes(:fun_facts).order("RANDOM()").limit(CARD_SIZE)
    random_fun_fact_ids = users.map do |user|
      user.fun_facts.shuffle[0].id
    end

    generated = false

    until generated
      generated_card = self.create(fun_fact_ids: random_fun_fact_ids)
      generated = generated_card.persisted?
    end

    generated_card
  end

  # Super inneficient but we need to maintain order
  def fun_facts
    @fun_facts ||= fun_fact_ids.map do |id|
      FunFact.find(id)
    end
  end

  def squares
    fun_facts.insert(fun_facts.length / 2, FunFact.new(text: "Free Space"))
  end
end

app/models/fun_fact.rb
class FunFact < ActiveRecord::Base
  MAXIMUM_PER_USER = 2

  belongs_to :user

  validates :user, presence: true
  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :fun_facts

  validates :email, presence: true
  validate :whitelisted_email, if: -> { self.class.email_whitelist? }

  def self.find_or_create_from_omniauth(auth)
    find_and_update_from_omniauth(auth) or create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.image = auth["info"]["image"]
    end
  end

  def self.find_and_update_from_omniauth(auth)
    find_by(auth.slice("provider","uid")).tap do |user|
      user && user.update_attribute(:image, auth["info"]["image"])
    end
  end

  def to_s
    self.name || self.email
  end

  def exceeds_fun_fact_limit?
    fun_facts.count >= FunFact::MAXIMUM_PER_USER
  end

  private

  def self.email_whitelist?
    !!ENV['EMAIL_WHITELIST']
  end

  def email_whitelist
    ENV["EMAIL_WHITELIST"].split(":")
  end

  def whitelisted_email
    if email_whitelist.none? { |email| self.email.include?(email) }
      errors.add(:email, "doesn't match the email domain whitelist: #{email_whitelist}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end
  helper_method :current_user

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def admin_user?
    current_user && current_user.admin?
  end
  helper_method :admin_user?

  def authenticate_user!
    if current_user
      true
    else
      session["return_to"] ||= request.url
      redirect_to login_path unless login_redirect? or oauth_callback?
    end
  end
  helper_method :authenticate_user!

  def authorize_admin!
    if admin_user?
      true
    else
      redirect_to :root
    end
  end
  helper_method :authorize_admin!

  def login_redirect?
    request.path == login_path
  end

  def oauth_callback?
    request.path == oauth_callback_path("google_oauth2")
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :authorize_admin!

  def index
    @cards = Card.all

    render :index, layout: 'plain'
  end

  def regen
    if FunFact.count >= Card::CARD_SIZE
      Card.destroy_all

      User.count.times do
        Card.generate
      end
    else
      flash[:error] = "Not enough fun facts to re-generate cards."
    end

    redirect_to cards_url
  end
end

app/controllers/fun_facts_controller.rb
class FunFactsController < ApplicationController
  before_filter :find_fun_fact, only: [:edit, :update, :destroy]
  before_filter :enforce_fun_fact_limit, only: [:new, :create]

  def index
    @fun_facts = current_user.fun_facts
  end

  def new
    @fun_fact = current_user.fun_facts.build
  end

  def create
    @fun_fact = current_user.fun_facts.create(fun_fact_params)
    redirect_to fun_facts_url
  end

  def edit
  end

  def update
    @fun_fact.update_attributes(fun_fact_params)
    redirect_to fun_facts_url
  end

  def destroy
    @fun_fact.destroy
    redirect_to fun_facts_url
  end

  private

  def find_fun_fact
    @fun_fact = current_user.fun_facts.find(params[:id])
  end

  def fun_fact_params
    params.require(:fun_fact).permit(:text)
  end

  def enforce_fun_fact_limit
    if current_user.exceeds_fun_fact_limit?
      flash[:error] = "Hey you! You already have 2 facts, delete one if you want to add another."
      redirect_to :root
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    origin = { origin: session.delete(:return_to) }.to_query
    redirect_to("/auth/google_oauth2?#{origin}")
  end

  def create
    user = User.find_or_create_from_omniauth(auth_hash)
    if user.valid?
      session[:user_id] = user.id
      flash[:notice] = "Signed in!"
      # OmniAuth automatically saves the HTTP_REFERER when you begin the auth process
      redirect_to  request.env['omniauth.origin'] || root_url
    else
      flash[:error] = "You need a #{ENV.fetch('APP_DOMAIN')} account to sign in."
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  protected

  def auth_hash
    # calling to_h because Strong Parameters don't allow direct access
    # to request parameters, even when passed to a class outside the
    # controller scope.
    request.env['omniauth.auth'].to_h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_card.html.haml
.bingo-card
  %h1
    Fun Fact Bingo
    %small ##{card.id}
  .bingo-card-inner
    %table
      - card.squares.in_groups_of(5) do |row|
        %tr
          - row.compact.each do |square|
            %td= square.text

app/views/cards/index.html.haml
= render @cards

app/views/fun_facts/_form.html.haml
.card
  = simple_form_for @fun_fact do |f|
    = f.input :text
    = f.button :submit

app/views/fun_facts/_fun_fact.html.haml
%tr.table-row
  %td.table-data= fun_fact.text
  %td.table-data.tar
    = link_to "edit", edit_fun_fact_path(fun_fact), class: 'btn btn--inline'
    = link_to "delete", fun_fact_path(fun_fact), method: :delete, class: 'btn btn--inline'

app/views/fun_facts/edit.html.haml
%h1 Edit Fun Fact for #{current_user.name}

= render 'form'

app/views/fun_facts/index.html.haml
.fr= link_to "New Fun Fact", new_fun_fact_path, class: 'btn'

%h1 Fun Facts for #{current_user.name}

.well
  .card
    %table.table
      %tbody.table-body= render @fun_facts

app/views/fun_facts/new.html.haml
%h1 New Fun Fact for #{current_user.name}

= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FunFactBingo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %h1 FUN FACT BINGO
    - if admin_user?
      %ul
        %li= link_to "Print Cards", cards_path
        %li= link_to "Regenerate Cards", regen_cards_path

    = yield

app/views/layouts/plain.html.haml
!!!
%html.plain
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FunFactBingo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield